// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJN89Ftbt8MQdazk_glW_ujeLKIN1SrxI',
    appId: '1:474241887532:web:0de8785b1de21fafb01089',
    messagingSenderId: '474241887532',
    projectId: 'flutter-chat-app-12e20',
    authDomain: 'flutter-chat-app-12e20.firebaseapp.com',
    storageBucket: 'flutter-chat-app-12e20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfNEkcBKVvXl7CbNPcHn4uM5fUinG-m5I',
    appId: '1:474241887532:android:511a4caef9c72791b01089',
    messagingSenderId: '474241887532',
    projectId: 'flutter-chat-app-12e20',
    storageBucket: 'flutter-chat-app-12e20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOEvUWEQRY0ZCYPuYPCmsIMkvD73q0tg',
    appId: '1:474241887532:ios:747d954b23a5c9e9b01089',
    messagingSenderId: '474241887532',
    projectId: 'flutter-chat-app-12e20',
    storageBucket: 'flutter-chat-app-12e20.appspot.com',
    iosBundleId: 'com.example.expiryTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEOEvUWEQRY0ZCYPuYPCmsIMkvD73q0tg',
    appId: '1:474241887532:ios:747d954b23a5c9e9b01089',
    messagingSenderId: '474241887532',
    projectId: 'flutter-chat-app-12e20',
    storageBucket: 'flutter-chat-app-12e20.appspot.com',
    iosBundleId: 'com.example.expiryTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr7ffVSwTLXMWfgaJ7S45aRHzLjipRpK8',
    appId: '1:474241887532:web:37b6b165fddddf63b01089',
    messagingSenderId: '474241887532',
    projectId: 'flutter-chat-app-12e20',
    authDomain: 'flutter-chat-app-12e20.firebaseapp.com',
    storageBucket: 'flutter-chat-app-12e20.appspot.com',
  );
}
