// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ffDC4Cf0MZDrqAQV2KgPXoRHZe4hIyc',
    appId: '1:990393978427:web:92ca9d3b35111aa991961e',
    messagingSenderId: '990393978427',
    projectId: 'expiry-track-efba5',
    authDomain: 'expiry-track-efba5.firebaseapp.com',
    storageBucket: 'expiry-track-efba5.appspot.com',
    measurementId: 'G-TPMHCK0BY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHb_9KnU_XLOPLcr2uK1U3txiBUMMcc94',
    appId: '1:990393978427:android:8e7f4dc2a5214dd991961e',
    messagingSenderId: '990393978427',
    projectId: 'expiry-track-efba5',
    storageBucket: 'expiry-track-efba5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHK_IdYqeWzGS_S2OqbzrD9xYxxLSsuLo',
    appId: '1:990393978427:ios:6825ee61e0b4843b91961e',
    messagingSenderId: '990393978427',
    projectId: 'expiry-track-efba5',
    storageBucket: 'expiry-track-efba5.appspot.com',
    iosBundleId: 'com.example.expiryTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHK_IdYqeWzGS_S2OqbzrD9xYxxLSsuLo',
    appId: '1:990393978427:ios:6825ee61e0b4843b91961e',
    messagingSenderId: '990393978427',
    projectId: 'expiry-track-efba5',
    storageBucket: 'expiry-track-efba5.appspot.com',
    iosBundleId: 'com.example.expiryTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_ffDC4Cf0MZDrqAQV2KgPXoRHZe4hIyc',
    appId: '1:990393978427:web:bc78f720ca2fcaaa91961e',
    messagingSenderId: '990393978427',
    projectId: 'expiry-track-efba5',
    authDomain: 'expiry-track-efba5.firebaseapp.com',
    storageBucket: 'expiry-track-efba5.appspot.com',
    measurementId: 'G-F11BV6KVXP',
  );
}
